-- MySQL Script generated by MySQL Workbench
-- Thu Jan 22 16:55:34 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema miniblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema miniblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miniblog` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `miniblog` ;

-- -----------------------------------------------------
-- Table `miniblog`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`user` (
  `id` INT(16) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `created_at` TIMESTAMP(0) NOT NULL COMMENT '\n',
  `modified_at` TIMESTAMP(0) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `firstname` (`firstname` ASC),
  INDEX `lastname` (`lastname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`post` (
  `id` INT(20) NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP(0) NOT NULL,
  `modified_at` TIMESTAMP(0) NOT NULL,
  `status` TINYINT(16) NOT NULL,
  `user_id` INT(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `description` (`description` ASC),
  INDEX `fk_post_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `miniblog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`comment` (
  `id` INT(20) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP(0) NOT NULL,
  `modified_at` TIMESTAMP(0) NOT NULL,
  `user_id1` INT(16) NOT NULL,
  `post_id` INT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`user_id1` ASC),
  INDEX `fk_comment_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id1`)
    REFERENCES `miniblog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `miniblog`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`token` (
  `id` INT(20) NOT NULL,
  `access_token` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP(0) NULL,
  `expired` TIMESTAMP(0) NULL,
  `user_id` INT(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_token_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_token_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `miniblog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
