-- MySQL Script generated by MySQL Workbench
-- Fri Jan 30 17:34:54 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema miniblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema miniblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miniblog` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `miniblog` ;

-- -----------------------------------------------------
-- Table `miniblog`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`Users` (
  `id` INT(16) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `image` VARCHAR(256) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT 0 COMMENT '\n',
  `modified_at` TIMESTAMP NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`Posts` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(256) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT 0,
  `modified_at` TIMESTAMP NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL,
  `image` VARCHAR(256) NULL,
  `user_id` INT(16) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_post_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `miniblog`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`Comments` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT 0,
  `modified_at` TIMESTAMP NOT NULL DEFAULT 0,
  `user_id` INT(16) NOT NULL,
  `post_id` INT(20) NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `post_id`),
  INDEX `fk_comment_user_idx` (`user_id` ASC),
  INDEX `fk_comment_post_idx` (`post_id` ASC),
  CONSTRAINT `fk_comment_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `miniblog`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `miniblog`.`Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`Tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `miniblog`.`Tokens` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `access_token` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT 0,
  `expired` TIMESTAMP NOT NULL DEFAULT 0,
  `user_id` INT(16) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_token_user_idx` (`user_id` ASC),
  UNIQUE INDEX `access_token_UNIQUE` (`access_token` ASC),
  CONSTRAINT `fk_token_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `miniblog`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
